name: Sondeo Maxiconsumo
on:
  push:
    paths: [".github/workflows/sondeo.yml", "herramientas/maxi_listar.py"]
permissions:
  contents: write
jobs:
  s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python herramientas/maxi_listar.py almacen bebidas frescos congelados limpieza perfumeria hogar-y-bazar mascotas
          git config user.name "github-actions[bot]"
          git config user.email "41898699+github-actions[bot]@users.noreply.github.com"
          git add herramientas/maxi_productos.json && git commit -q -m "sondeo (temporal)" && git push
